### ISSUE TITLE
diff_analysis.py error--'NoneType' object has no attribute 'contents'

### ISSUE THREAD

**Issue by chengwuxinlin** [pauls658/ReluDiff-ICSE2020-Artifact#1]
Hello, I tired to run `python3 diff_analysis.py mnist-global` but it gave me an error.

Problem with loading/calling "ffn_handle_first_relu_layer" from "libfppoly.so"
/usr/local/lib/libfppoly.so: undefined symbol: ffn_handle_first_relu_layer
the layer does not exist
the layer does not exist
Problem with loading/calling "ffn_handle_intermediate_relu_layer" from "libfppoly.so"
/usr/local/lib/libfppoly.so: undefined symbol: ffn_handle_intermediate_relu_layer
the layer does not exist
the layer does not exist
Problem with loading/calling "ffn_handle_last_relu_layer" from "libfppoly.so"
/usr/local/lib/libfppoly.so: undefined symbol: ffn_handle_last_relu_layer
the layer does not exist
the layer does not exist
Problem with loading/calling "subtract_output_neurons" from "libfppoly.so"
/usr/local/lib/libfppoly.so: undefined symbol: subtract_output_neurons
Traceback (most recent call last):
  File "diff_analysis.py", line 363, in <module>
    runMNIST()
  File "diff_analysis.py", line 315, in runMNIST
    res = getEps2(eran, lb, ub, target, 10)
  File "diff_analysis.py", line 30, in getEps2
    return (elapsed, res.contents.sup.contents.val.dbl, res.contents.inf.contents.val.dbl)
AttributeError: 'NoneType' object has no attribute 'contents'

Looks like the function getEps2 return a None for the res, just wonder is there anyway I can fix that?

Thanks!

**Comment by pauls658** [comment]
Hello,

It looks like this error is specific to DeepPoly/ERAN, so the help I can give is limited, and the script you mention works for me on the artifact's VM. Are you using the provided VM, or did you install it on your own machine?
Also, the error message "the layer does not exist" suggests that maybe there is a problem with the neural net files stored in `eran/NNet/nnet/mnist_*`, maybe they got removed or corrupted accidentally.

Hope this helps!

**Comment by chengwuxinlin** [comment]
I followed [https://github.com/pauls658/ReluDiff-ICSE2020-Artifact/blob/master/INSTALL.md](url) for setting up each of the tools on Ubuntu

I think the net files are good because I can load them separately. Also, I can run `bash scripts/run_MNIST-global_exec-time_experiments.sh` fine but not the Python file.

**Comment by pauls658** [comment]
The `bash scripts/run_MNIST-global_exec-time_experiments.sh` script doesn't actually run the DeepPoly/eran tool, so there isn't any issue there.

Are you running `python3 diff_analysis.py mnist-global` from the directory `eran/tf_verify`?

**Comment by pauls658** [comment]
Also, are the library paths set correctly? What is the output of `echo $LIBRARY_PATH`?

**Comment by chengwuxinlin** [comment]
I think it is the library issue. On my side, The `./install.sh $INSTALL_PREFIX` still install eran to system lib, not the custom address. I will just run sh file in this case then.

Additionally, I have two more questions.
If I want to try other MNIST samples, I should edit the `mnist_tests.h` before compiling `make clean all` right? Same as eps, if I want to try different eps values, I can change it in `run_MNIST-global_exec-time_experiments.sh`? (might be a silly question, but I'm not familiar with sh file)

I assume the output `No adv!` stands for no adversarial samples found. Please tell me if I misunderstood it.

Thank you so much for your patience and detailed reply

**Comment by pauls658** [comment]
I think you are right on it being a library issue. Sorry I couldn't be more help.

> If I want to try other MNIST samples, I should edit the mnist_tests.h before compiling make clean all right? Same as eps, if I want to try different eps values, I can change it in run_MNIST-global_exec-time_experiments.sh?

Yes you are correct. You should edit mnist_test.h and then recompile. And yes, you can edit the `eps` variable in `run_MNIST-global_exec-time_experiments.sh`.

> I assume the output No adv! stands for no adversarial samples found. Please tell me if I misunderstood it.

That's correct.

Let me know if you have any more questions!
